# -----------------
# DCustomRPC Config
# -----------------
# Please read the README.md before asking for support.

# The client ID of the application you made on the Discord Developers page.
client_id: 814550660544200725

# Enable GUI? If enabled, this will result in a pop-up box when a exception happens. If Discord is closed, this can get *very* annoying, so disabled by default.
enable_gui: false

game_cycle:
  # The time until the game cycles in seconds.
  time_until_cycle: 10

  games:
    # The list of games that it will cycle through.
    - details: "Hi there!"
      state: "I'm 0/0! Keep a eye on this status for more info."
      large_image: "profile_pic"
      large_text: "This updates every 10 seconds."
      buttons:
        - label: "My Website"
          url: "https://imaskeleton.me"

    - details: "Powered by DCustomRPC!"
      state: "This custom rich presence integration is powered by DCustomRPC."
      large_image: "discord"
      buttons:
        - label: "Click for link!"
          url: "https://github.com/tazz4843/DCustomRPC"

    - details: "COVID-19 Bot"
      state: "The single best COVID-19 bot for Discord!"
      large_image: "covid_bot"
      large_text: "yes it is the best don't fight me here"
      buttons:
        - label: "Invite the Bot"
          url: "https://covid19.imaskeleton.me/invite"
        - label: "Support Server"
          url: "https://discord.gg/5yXExTsRye"

    - details: "@someone"
      state: "Let's bring back Discord's 2018 April Fools!"
      large_image: "someone"
      large_text: "*ping noises*"
      buttons:
        - label: "Invite the Bot"
          url: "https://discord.com/api/oauth2/authorize?client_id=800865331072729109&permissions=67468352&redirect_uri=https%3A%2F%2Fdiscord.com%2Foauth2%2Fauthorized&scope=bot"
        - label: "Support Server"
          url: "https://discord.gg/5yXExTsRye"

    - details: "Scripty"
      state: "Free speech to text for voice chats!"
      large_image: "scripty"
      large_text: "written in Rust, so Rust best"
      buttons:
        - label: "Invite the Bot"
          url: "https://scripty.imaskeleton.me/invite"
        - label: "Support Server"
          url: "https://discord.gg/5yXExTsRye"

    - details: "Creating Discord bots!"
      state: "If you need a special bot, shoot me a DM."
      large_image: "discord"
      large_text: "prices vary from $3 to up to $45"
      buttons:
        - label: "Get in Touch"
          url: "https://discord.gg/5yXExTsRye"

    - details: "monke"
      state: "DM for the chance to win a IRL monke"
      large_image: "monkey"
      large_text: "monke"

    - details: "That's all!"
      state: "If you want to get in touch, shoot me a DM or join my server."
      large_image: "waving_hand"
      large_text: "stop reading this ffs"
      buttons:
        - label: "My Server"
          url: "https://discord.gg/5yXExTsRye"
